---
version: "3"
services:
  python:
    image: ${HHC_IMAGE}
    userns_mode: "host"
    env_file: .env
    working_dir: /opt/app
    volumes:
      - ~/.aws:/root/.aws
      - .:/opt/app:rw

  terraform:
    image: hashicorp/terraform:1.3.6
    userns_mode: "host"
    env_file: .env
    working_dir: /opt/app/infra
    volumes:
      - ~/.aws:/root/.aws
      - .:/opt/app:rw

  sonar:
    image: sonarsource/sonar-scanner-cli:latest
    userns_mode: "host"
    env_file: .env
    working_dir: /usr/src
    volumes:
      - .:/usr/src:rw

  awscli:
    image: amazon/aws-cli:latest
    userns_mode: "host"
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws
